version: '2'
services:
  web:
    # thinlt/apache-php available tags: latest, 7.2, 5.6.
    image: thinlt/lamp:1.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      ## Data.
      - ./data/www:/var/www/html
      - ./data/mysql:/var/lib/mysql
