version: '2'
services:
  starter-m2:
    # thinlt/apache-php available tags: latest, 7.2, 5.6.
    image: thinlt/omnichannel_magento2
    container_name: starter_m2
    ports:
    - "81:80"
    - "4431:443"
    #  - "3306:3306"
    volumes:
      ## Data.
      - ./data/www:/var/www/html
      - ./data/mysql:/var/lib/mysql
      - ./config/apache2:/etc/apache2
